//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opinion
    {
        public int ID { get; set; }
        public int opinionID { get; set; }
        public int reportID { get; set; }
        public int projectID { get; set; }
        public string userCreatedID { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public string opinion1 { get; set; }
    
        public virtual Report Report { get; set; }
        public virtual Project Project { get; set; }
    }
}
