//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Report()
        {
            this.Opinions = new HashSet<Opinion>();
        }
    
        public int ID { get; set; }
        public int reportID { get; set; }
        public int projectID { get; set; }
        public string reportName { get; set; }
        public int userCreatedID { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<int> userReviewedID { get; set; }
        public Nullable<System.DateTime> dateReviewed { get; set; }
        public Nullable<int> userApprovedID { get; set; }
        public Nullable<System.DateTime> dateApproved { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> duration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opinion> Opinions { get; set; }
        public virtual Project Project { get; set; }
    }
}
